/*--------------------------------------------------------------------------
 * This file is autogenerated from EBV_ProjectConfig.h.cmake 
 * during the cmake configuration of your project. If you need to make changes
 * edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/
#ifndef EBV_PROJECTCONFIG_H
#define EBV_PROJECTCONFIG_H

/* Define to 1 if you have CUDA */
/* #undef WITH_CUDA */

/* Define to 1 if you have ArrayFire */
/* #undef WITH_ArrayFire */

/* Define to 1 if you have Qt5 */
/* #undef WITH_Qt5 */

/* Define to 1 if you have OpenCV */
/* #undef WITH_OpenCV */

/* Define to 1 if you have LibUSB */
/* #undef WITH_LibUSB */

/* Define to 1 if you have LibATIS */
/* #undef WITH_LibATIS */

/* Define to 1 if you have OpenNI2 */
/* #undef WITH_OpenNI2 */

#endif //EBV_PROJECTCONFIG_H

